package DCCardGame;

import java.awt.*;
import javax.swing.ScrollPaneConstants;
import javax.swing.border.*;
/******************************************************************************
 * @author Logan
 *****************************************************************************/
public class TestFrame extends javax.swing.JFrame {

    /** Creates new form TestFrame */
    public TestFrame() {
        initComponents();
        //testScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        testPanel.setLayout(new GridLayout(1,0, 5, 5));
        //Border empty = new EmptyBorder(0,5,0,5);
        //testPanel.setBorder(empty);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerDeckMainPanel = new javax.swing.JPanel();
        discardPilePanel = new javax.swing.JPanel();
        discardPile = new javax.swing.JLabel();
        playerDeckPanel = new javax.swing.JPanel();
        playerDeck = new javax.swing.JLabel();
        extraLineupSlot1 = new javax.swing.JLabel();
        extraLineupSlot2 = new javax.swing.JLabel();
        extraLineupSlot3 = new javax.swing.JLabel();
        extraLineupSlot4 = new javax.swing.JLabel();
        extraLineupSlot5 = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        drawCardButton = new javax.swing.JButton();
        mainDeckPeekButton = new javax.swing.JButton();
        deckPeekButton = new javax.swing.JButton();
        currentPowerLabel = new javax.swing.JLabel();
        deckScoreLabel = new javax.swing.JLabel();
        currentPowerTextBox = new javax.swing.JTextField();
        deckScoreTextBox = new javax.swing.JTextField();
        drawWeaknessButton = new javax.swing.JButton();
        destroyCardButton = new javax.swing.JButton();
        discardCardButton = new javax.swing.JButton();
        searchDiscardsButton = new javax.swing.JButton();
        drawHandButton1 = new javax.swing.JButton();
        discardHandButton = new javax.swing.JButton();
        mainDeckDraw = new javax.swing.JButton();
        printDeckButton = new javax.swing.JButton();
        printDiscards = new javax.swing.JButton();
        superHeroMainPanel = new javax.swing.JPanel();
        superHeroPanel = new javax.swing.JPanel();
        superHeroSlot = new javax.swing.JLabel();
        kickDeckMainPanel = new javax.swing.JPanel();
        kickDeckPanel = new javax.swing.JPanel();
        kickDeck = new javax.swing.JLabel();
        lineupPanel = new javax.swing.JPanel();
        lineupPanel1 = new javax.swing.JPanel();
        lineupSlot1 = new javax.swing.JLabel();
        lineupPanel2 = new javax.swing.JPanel();
        lineupSlot2 = new javax.swing.JLabel();
        lineupPanel3 = new javax.swing.JPanel();
        lineupSlot3 = new javax.swing.JLabel();
        lineupPanel4 = new javax.swing.JPanel();
        lineupSlot4 = new javax.swing.JLabel();
        lineupPanel5 = new javax.swing.JPanel();
        lineupSlot5 = new javax.swing.JLabel();
        mainDeckMainPanel = new javax.swing.JPanel();
        mainDeckPanel = new javax.swing.JPanel();
        mainDeck = new javax.swing.JLabel();
        testScrollPane = new javax.swing.JScrollPane();
        testPanel = new javax.swing.JPanel();
        playerHandSlot1 = new javax.swing.JLabel();
        playerHandSlot2 = new javax.swing.JLabel();
        playerHandSlot3 = new javax.swing.JLabel();
        playerHandSlot6 = new javax.swing.JLabel();
        playerHandSlot4 = new javax.swing.JLabel();
        playerHandSlot5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerDeckMainPanel.setBackground(new java.awt.Color(144, 154, 178));
        playerDeckMainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        discardPilePanel.setBackground(new java.awt.Color(144, 154, 178));
        discardPilePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        discardPile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Empty Discard.png"))); // NOI18N

        javax.swing.GroupLayout discardPilePanelLayout = new javax.swing.GroupLayout(discardPilePanel);
        discardPilePanel.setLayout(discardPilePanelLayout);
        discardPilePanelLayout.setHorizontalGroup(
            discardPilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discardPilePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(discardPile)
                .addGap(5, 5, 5))
        );
        discardPilePanelLayout.setVerticalGroup(
            discardPilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discardPilePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(discardPile)
                .addGap(5, 5, 5))
        );

        playerDeckPanel.setBackground(new java.awt.Color(144, 154, 178));
        playerDeckPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        playerDeck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Card Back.png"))); // NOI18N
        playerDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerDeckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout playerDeckPanelLayout = new javax.swing.GroupLayout(playerDeckPanel);
        playerDeckPanel.setLayout(playerDeckPanelLayout);
        playerDeckPanelLayout.setHorizontalGroup(
            playerDeckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerDeckPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(playerDeck)
                .addGap(5, 5, 5))
        );
        playerDeckPanelLayout.setVerticalGroup(
            playerDeckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerDeckPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(playerDeck)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout playerDeckMainPanelLayout = new javax.swing.GroupLayout(playerDeckMainPanel);
        playerDeckMainPanel.setLayout(playerDeckMainPanelLayout);
        playerDeckMainPanelLayout.setHorizontalGroup(
            playerDeckMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerDeckMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(discardPilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerDeckMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerDeckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        playerDeckMainPanelLayout.setVerticalGroup(
            playerDeckMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerDeckMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(discardPilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerDeckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        extraLineupSlot1.setBackground(new java.awt.Color(144, 154, 178));
        extraLineupSlot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        extraLineupSlot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        extraLineupSlot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        extraLineupSlot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        extraLineupSlot5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        controlPanel.setBackground(new java.awt.Color(144, 154, 178));
        controlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        drawCardButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        drawCardButton.setText("Draw Single Card");

        mainDeckPeekButton.setText("Main Deck Peek");

        deckPeekButton.setText("Deck Peek");

        currentPowerLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        currentPowerLabel.setText("Current Power");

        deckScoreLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deckScoreLabel.setText("Deck Score");

        currentPowerTextBox.setEditable(false);
        currentPowerTextBox.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        currentPowerTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        currentPowerTextBox.setText("0");

        deckScoreTextBox.setEditable(false);
        deckScoreTextBox.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        deckScoreTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deckScoreTextBox.setText("0");

        drawWeaknessButton.setText("Draw Weakness");
        drawWeaknessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawWeaknessButtonActionPerformed(evt);
            }
        });

        destroyCardButton.setText("Destroy Cards");

        discardCardButton.setText("Discard Card");

        searchDiscardsButton.setText("Search Discards");

        drawHandButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        drawHandButton1.setText("Draw Hand");

        discardHandButton.setText("Discard Hand");

        mainDeckDraw.setText("Main Deck Draw");

        printDeckButton.setText("printDeckButton");
        printDeckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDeckButtonActionPerformed(evt);
            }
        });

        printDiscards.setText("printDiscards");
        printDiscards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDiscardsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(currentPowerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentPowerLabel)
                        .addGap(31, 31, 31)))
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deckScoreTextBox)
                    .addComponent(deckScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drawHandButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deckPeekButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destroyCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drawWeaknessButton)
                            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(discardHandButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainDeckPeekButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addComponent(mainDeckDraw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(searchDiscardsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(discardCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(printDeckButton)
                            .addComponent(printDiscards))))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deckScoreLabel)
                    .addComponent(currentPowerLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPowerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deckScoreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainDeckDraw)
                    .addComponent(printDiscards))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawWeaknessButton)
                    .addComponent(printDeckButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discardHandButton)
                    .addComponent(discardCardButton)
                    .addComponent(destroyCardButton))
                .addGap(7, 7, 7)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDiscardsButton)
                    .addComponent(mainDeckPeekButton)
                    .addComponent(deckPeekButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawHandButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        superHeroMainPanel.setBackground(new java.awt.Color(144, 154, 178));
        superHeroMainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        superHeroPanel.setBackground(new java.awt.Color(144, 154, 178));
        superHeroPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        superHeroSlot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Super Hero Back.png"))); // NOI18N
        superHeroSlot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                superHeroSlotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout superHeroPanelLayout = new javax.swing.GroupLayout(superHeroPanel);
        superHeroPanel.setLayout(superHeroPanelLayout);
        superHeroPanelLayout.setHorizontalGroup(
            superHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superHeroPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(superHeroSlot)
                .addGap(10, 10, 10))
        );
        superHeroPanelLayout.setVerticalGroup(
            superHeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superHeroPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(superHeroSlot)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout superHeroMainPanelLayout = new javax.swing.GroupLayout(superHeroMainPanel);
        superHeroMainPanel.setLayout(superHeroMainPanelLayout);
        superHeroMainPanelLayout.setHorizontalGroup(
            superHeroMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superHeroMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(superHeroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        superHeroMainPanelLayout.setVerticalGroup(
            superHeroMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superHeroMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(superHeroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        kickDeckMainPanel.setBackground(new java.awt.Color(144, 154, 178));
        kickDeckMainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        kickDeckPanel.setBackground(new java.awt.Color(144, 154, 178));
        kickDeckPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        kickDeck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Kick/Kick.png"))); // NOI18N
        kickDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kickDeckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kickDeckMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout kickDeckPanelLayout = new javax.swing.GroupLayout(kickDeckPanel);
        kickDeckPanel.setLayout(kickDeckPanelLayout);
        kickDeckPanelLayout.setHorizontalGroup(
            kickDeckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kickDeckPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(kickDeck)
                .addGap(5, 5, 5))
        );
        kickDeckPanelLayout.setVerticalGroup(
            kickDeckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kickDeckPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(kickDeck)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout kickDeckMainPanelLayout = new javax.swing.GroupLayout(kickDeckMainPanel);
        kickDeckMainPanel.setLayout(kickDeckMainPanelLayout);
        kickDeckMainPanelLayout.setHorizontalGroup(
            kickDeckMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kickDeckMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(kickDeckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        kickDeckMainPanelLayout.setVerticalGroup(
            kickDeckMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kickDeckMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(kickDeckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        lineupPanel.setBackground(new java.awt.Color(144, 154, 178));
        lineupPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lineupPanel1.setBackground(new java.awt.Color(144, 154, 178));
        lineupPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lineupSlot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Empty Card Slot.png"))); // NOI18N
        lineupSlot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineupSlot1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lineupPanel1Layout = new javax.swing.GroupLayout(lineupPanel1);
        lineupPanel1.setLayout(lineupPanel1Layout);
        lineupPanel1Layout.setHorizontalGroup(
            lineupPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot1)
                .addGap(5, 5, 5))
        );
        lineupPanel1Layout.setVerticalGroup(
            lineupPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        lineupPanel2.setBackground(new java.awt.Color(144, 154, 178));
        lineupPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lineupSlot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Empty Card Slot.png"))); // NOI18N
        lineupSlot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineupSlot2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lineupPanel2Layout = new javax.swing.GroupLayout(lineupPanel2);
        lineupPanel2.setLayout(lineupPanel2Layout);
        lineupPanel2Layout.setHorizontalGroup(
            lineupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot2)
                .addGap(5, 5, 5))
        );
        lineupPanel2Layout.setVerticalGroup(
            lineupPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        lineupPanel3.setBackground(new java.awt.Color(144, 154, 178));
        lineupPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lineupSlot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Empty Card Slot.png"))); // NOI18N
        lineupSlot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineupSlot3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lineupPanel3Layout = new javax.swing.GroupLayout(lineupPanel3);
        lineupPanel3.setLayout(lineupPanel3Layout);
        lineupPanel3Layout.setHorizontalGroup(
            lineupPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot3)
                .addGap(5, 5, 5))
        );
        lineupPanel3Layout.setVerticalGroup(
            lineupPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot3)
                .addGap(5, 5, 5))
        );

        lineupPanel4.setBackground(new java.awt.Color(144, 154, 178));
        lineupPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lineupSlot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Empty Card Slot.png"))); // NOI18N

        javax.swing.GroupLayout lineupPanel4Layout = new javax.swing.GroupLayout(lineupPanel4);
        lineupPanel4.setLayout(lineupPanel4Layout);
        lineupPanel4Layout.setHorizontalGroup(
            lineupPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot4)
                .addGap(5, 5, 5))
        );
        lineupPanel4Layout.setVerticalGroup(
            lineupPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lineupPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot4))
        );

        lineupPanel5.setBackground(new java.awt.Color(144, 154, 178));
        lineupPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lineupSlot5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Empty Card Slot.png"))); // NOI18N
        lineupSlot5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineupSlot5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lineupPanel5Layout = new javax.swing.GroupLayout(lineupPanel5);
        lineupPanel5.setLayout(lineupPanel5Layout);
        lineupPanel5Layout.setHorizontalGroup(
            lineupPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot5)
                .addGap(5, 5, 5))
        );
        lineupPanel5Layout.setVerticalGroup(
            lineupPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lineupSlot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout lineupPanelLayout = new javax.swing.GroupLayout(lineupPanel);
        lineupPanel.setLayout(lineupPanelLayout);
        lineupPanelLayout.setHorizontalGroup(
            lineupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lineupPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lineupPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lineupPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lineupPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lineupPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        lineupPanelLayout.setVerticalGroup(
            lineupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineupPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(lineupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lineupPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lineupPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineupPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lineupPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lineupPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        mainDeckMainPanel.setBackground(new java.awt.Color(144, 154, 178));
        mainDeckMainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mainDeckPanel.setBackground(new java.awt.Color(144, 154, 178));
        mainDeckPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainDeck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Card Back.png"))); // NOI18N

        javax.swing.GroupLayout mainDeckPanelLayout = new javax.swing.GroupLayout(mainDeckPanel);
        mainDeckPanel.setLayout(mainDeckPanelLayout);
        mainDeckPanelLayout.setHorizontalGroup(
            mainDeckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDeckPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(mainDeck)
                .addGap(5, 5, 5))
        );
        mainDeckPanelLayout.setVerticalGroup(
            mainDeckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDeckPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(mainDeck)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout mainDeckMainPanelLayout = new javax.swing.GroupLayout(mainDeckMainPanel);
        mainDeckMainPanel.setLayout(mainDeckMainPanelLayout);
        mainDeckMainPanelLayout.setHorizontalGroup(
            mainDeckMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainDeckMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mainDeckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        mainDeckMainPanelLayout.setVerticalGroup(
            mainDeckMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainDeckMainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mainDeckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        testPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));

        playerHandSlot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        playerHandSlot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        playerHandSlot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        playerHandSlot6.setBackground(new java.awt.Color(144, 154, 178));
        playerHandSlot6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        playerHandSlot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        playerHandSlot5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DCCardGame/resources/Other Cards/Blank Card.png"))); // NOI18N

        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(playerHandSlot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerHandSlot6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerHandSlot2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerHandSlot4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerHandSlot3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerHandSlot5)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerHandSlot5)
                    .addComponent(playerHandSlot3)
                    .addComponent(playerHandSlot4)
                    .addComponent(playerHandSlot2)
                    .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(playerHandSlot6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerHandSlot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );

        testScrollPane.setViewportView(testPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainDeckMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lineupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kickDeckMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(extraLineupSlot1)
                                .addGap(44, 44, 44)
                                .addComponent(extraLineupSlot2)
                                .addGap(33, 33, 33)
                                .addComponent(extraLineupSlot3)
                                .addGap(30, 30, 30)
                                .addComponent(extraLineupSlot4)
                                .addGap(32, 32, 32)
                                .addComponent(extraLineupSlot5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(superHeroMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(testScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addComponent(playerDeckMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainDeckMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lineupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(extraLineupSlot4)
                                            .addComponent(extraLineupSlot5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(extraLineupSlot1)
                                        .addComponent(extraLineupSlot2)
                                        .addComponent(extraLineupSlot3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(kickDeckMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(testScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(superHeroMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(playerDeckMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerDeckMouseClicked
        
    }//GEN-LAST:event_playerDeckMouseClicked

    private void drawWeaknessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawWeaknessButtonActionPerformed
        
    }//GEN-LAST:event_drawWeaknessButtonActionPerformed

    private void printDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDeckButtonActionPerformed
       
    }//GEN-LAST:event_printDeckButtonActionPerformed

    private void printDiscardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDiscardsActionPerformed
       
    }//GEN-LAST:event_printDiscardsActionPerformed

    private void superHeroSlotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_superHeroSlotMouseClicked
        
    }//GEN-LAST:event_superHeroSlotMouseClicked

    private void kickDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kickDeckMouseClicked
        
    }//GEN-LAST:event_kickDeckMouseClicked

    private void kickDeckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kickDeckMouseEntered
        
    }//GEN-LAST:event_kickDeckMouseEntered

    private void lineupSlot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineupSlot1MouseClicked
        
    }//GEN-LAST:event_lineupSlot1MouseClicked

    private void lineupSlot2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineupSlot2MouseClicked
       
    }//GEN-LAST:event_lineupSlot2MouseClicked

    private void lineupSlot3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineupSlot3MouseClicked
        
    }//GEN-LAST:event_lineupSlot3MouseClicked

    private void lineupSlot5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineupSlot5MouseClicked
        
    }//GEN-LAST:event_lineupSlot5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel currentPowerLabel;
    private javax.swing.JTextField currentPowerTextBox;
    private javax.swing.JButton deckPeekButton;
    private javax.swing.JLabel deckScoreLabel;
    public static javax.swing.JTextField deckScoreTextBox;
    private javax.swing.JButton destroyCardButton;
    private javax.swing.JButton discardCardButton;
    private javax.swing.JButton discardHandButton;
    private javax.swing.JLabel discardPile;
    private javax.swing.JPanel discardPilePanel;
    private javax.swing.JButton drawCardButton;
    private javax.swing.JButton drawHandButton1;
    private javax.swing.JButton drawWeaknessButton;
    private javax.swing.JLabel extraLineupSlot1;
    private javax.swing.JLabel extraLineupSlot2;
    private javax.swing.JLabel extraLineupSlot3;
    private javax.swing.JLabel extraLineupSlot4;
    private javax.swing.JLabel extraLineupSlot5;
    private javax.swing.JLabel kickDeck;
    private javax.swing.JPanel kickDeckMainPanel;
    private javax.swing.JPanel kickDeckPanel;
    private javax.swing.JPanel lineupPanel;
    private javax.swing.JPanel lineupPanel1;
    private javax.swing.JPanel lineupPanel2;
    private javax.swing.JPanel lineupPanel3;
    private javax.swing.JPanel lineupPanel4;
    private javax.swing.JPanel lineupPanel5;
    private javax.swing.JLabel lineupSlot1;
    private javax.swing.JLabel lineupSlot2;
    private javax.swing.JLabel lineupSlot3;
    private javax.swing.JLabel lineupSlot4;
    private javax.swing.JLabel lineupSlot5;
    private javax.swing.JLabel mainDeck;
    private javax.swing.JButton mainDeckDraw;
    private javax.swing.JPanel mainDeckMainPanel;
    private javax.swing.JPanel mainDeckPanel;
    private javax.swing.JButton mainDeckPeekButton;
    private javax.swing.JLabel playerDeck;
    private javax.swing.JPanel playerDeckMainPanel;
    private javax.swing.JPanel playerDeckPanel;
    private javax.swing.JLabel playerHandSlot1;
    private javax.swing.JLabel playerHandSlot2;
    private javax.swing.JLabel playerHandSlot3;
    private javax.swing.JLabel playerHandSlot4;
    private javax.swing.JLabel playerHandSlot5;
    private javax.swing.JLabel playerHandSlot6;
    private javax.swing.JButton printDeckButton;
    private javax.swing.JButton printDiscards;
    private javax.swing.JButton searchDiscardsButton;
    private javax.swing.JPanel superHeroMainPanel;
    private javax.swing.JPanel superHeroPanel;
    private javax.swing.JLabel superHeroSlot;
    private javax.swing.JPanel testPanel;
    private javax.swing.JScrollPane testScrollPane;
    // End of variables declaration//GEN-END:variables

}
